- hosts: cluster
  become: yes
  tasks:
    - name: Install packages
      yum:
        name:
          - python3-pip
          - lsof
          - vim-minimal
        state: latest

    - name: Install Docker SDK
      pip:
        name: docker
